### ISSUE TITLE
Municipal Representatives scraper

### ISSUE THREAD

**Issue by akariv** [OpenBudget/budgetkey-data-pipelines#105]
In this file we have a list of all elected representatives in all municipalities

http://www.moin.gov.il/PressAnnouncements/Pages/%D7%91%D7%97%D7%99%D7%A8%D7%95%D7%AA-%D7%9C%D7%A8%D7%A9%D7%95%D7%99%D7%95%D7%AA-%D7%94%D7%9E%D7%A7%D7%95%D7%9E%D7%99%D7%95%D7%AA-----14-11-2013---.aspx

We'd like to write a pipeline to scrape this file and add it to the current 'people' pipelines as another role for each person.

**Comment by slallum** [comment]
I'm starting to working on it :)
