### ISSUE TITLE
Add Safety Orders information to construction companies - הפרות בטיחות באתרי הבנייה

### ISSUE THREAD

**Issue by akariv** [OpenBudget/budgetkey-data-pipelines#109]
In this link there's an 'orders.xls' file which contains a list of safety orders (הפרות בטיחות באתרי הבנייה).

http://employment.molsa.gov.il/Employment/SafetyAndHealth/Enforcement/Pages/SafetyOrdersList.aspx

We want to add this information to the relevant companies, so it's visible to users of the website viewing a company.

- [ ] write a pipeline that scrapes this data and saves it to a file + a db table (safety orders)
   - [ ] use the `fingerprint` processor to take a 'fingerprint' of the company name, and `join` it with the 'entity fingerprints' dataset to get the company ids and canonic names
   - [ ] use the `collate` processor to create an 'incident' object with the date and description of the security report
   - [ ] join the dataset with itself to generate a single record for each company, with an array of all incidents.
- [ ] then, add another step to the company details pipeline to join the result of the above pipeline output with the basic company information

**Comment by odedsh** [comment]
I noticed there is also.. 
http://employment.molsa.gov.il/Employment/SafetyAndHealth/Enforcement/Pages/ClosedSites.aspx
