### ISSUE TITLE
should ensure same version of datapackage-pipelines dependency runs on all environments

### ISSUE THREAD

**Issue by OriHoch** [OpenBudget/budgetkey-data-pipelines#11]
#### preconditions
* datapackage-pipelines version was published to pypi 
* but, docker file was not updated - so contains previous version
* however - code in budgetkey-data-pipelines relies on the latest version and breaks on previous datapackage-pipelines version

#### reproduction steps
* run the budgetkey-data-pipelines docker

##### expected
* docker should run with the latest pypi version which the code was tested against

##### Actual
* code fails because it runs with previous datapackage-pipelines version from docker
* we pull latest docker image which has the previous datapackage-pipelines version
  * `FROM frictionlessdata/datapackage-pipelines:latest`
* budgetkey-data-pipelines is installed like this:
  * `RUN sudo pip install -e / `
* setup.py doesn't contains the datapackage-pipelines dependency, so won't upgrade it (no --upgrade param)
* end up with previous datapackage-pipelines version

**Comment by akariv** [comment]
The problem here is actually the other way round - dpp docker image uses the version from the master branch (and by inheritance, also the budgetkey-data-pipelines). Locally you would usually use the latest published version, which might be a few commits behind the master version.
