### ISSUE TITLE
pulling code from remote master branch to origin master branch should not cause a merge commit

### ISSUE THREAD

**Issue by OriHoch** [OpenBudget/budgetkey-data-pipelines#12]
look at this merge commit - https://github.com/OriHoch/budgetkey-data-pipelines/commit/28bb9d8b98ea49d96f8bf966a0c32b08e8d01b00

it was done when I pulled latest changes from OpenBudget master branch to my master branch

my master branch didn't have any local changes, so it should be a fast-forward without a merge commit

the merge commit is for these 2 commits:
* cf8095ded128cd239a89af14c93df836bcf36be1 - this commit is on OpenBudget master branch
* f2899e6804fd613f73a570f2c7de55257a2d7672 - this commit is **not** on OpenBudget mastar branch

however, there is a commit which has the same title and time which is on OpenBudget master branch:
2dcd32e71fe7e124403ab71231b350e1ea56d014

not sure exactly what's going on here

@akariv - is it possible you are editing history?

**Comment by OriHoch** [comment]
BTW I think this happened before, not sure if it was the same problem or not..

currently to update my master branch, I have to delete it and create it again

**Comment by akariv** [comment]
This is probably my bad.
Since I'm always squashing when merging PRs there's no harm done, I think.
I'll try to avoid that in the future.

**Comment by OriHoch** [comment]
you just need to make sure you don't squash a commit which was already pushed to master branch

**Comment by akariv** [comment]
Squash is based on diffing the branches (regardless of participating
commits), so as long as the diff is ok there should be no problem.
(but either way I agree it's best to avoid this situation altogether).
