### ISSUE TITLE
Ministry of Education data from data.gov.il

### ISSUE THREAD

**Issue by asfuna** [OpenBudget/budgetkey-data-pipelines#122]
There're a few reports in https://data.gov.il/organization/ministry_of_education regarding budgets of schools, kindergartens, etc.
Here (https://data.gov.il/dataset/shkifut-budget-school-2016) for example, there is for each school, the total number of students, total hours taught, budgets of various types, number of classes, and so on. Could be interesting to create a way to compare schools

**Comment by akariv** [comment]
Opened a task for it 

https://github.com/OpenBudget/BudgetKey/issues/166
