### ISSUE TITLE
missing exemption data

### ISSUE THREAD

**Issue by VitalyLub** [OpenBudget/budgetkey-data-pipelines#37]
I don't find an exemption and I afraid that it's not the only one that missing

https://www.mr.gov.il/ExemptionMessage/Pages/ExemptionMessage.aspx?pID=592899

select *
from exemption e
where publication_id = 592899 or publication_id = '592899'

**Comment by OriHoch** [comment]
I just tested it with the new scraper - and this exemption is there

[exemptions.xlsx](https://github.com/OpenBudget/budgetkey-data-pipelines/files/1070577/exemptions.xlsx)


so this bug won't affect the new scraper (which should be ready soon..)

**Comment by OriHoch** [comment]
@VitalyLub - if you want I can send you similar excel with all the exemptions from past few months

**Comment by VitalyLub** [comment]
@OriHoch Thanks, but I don't really need the data for now.
Do you how many data we don't have at the DB right now?

**Comment by OriHoch** [comment]
:+1: 
I don't know, I just happen to work on the exemptions for the past weeks so I know the status of that..

**Comment by VitalyLub** [comment]
Cool
We will be happy to here when the new scraper is up :)

**Comment by akariv** [comment]
Scraper is up and running, data can be found in the `next-obudget` source under the `procurement_tenders_exemptions` table.

**Comment by VitalyLub** [comment]
Thanks!
what about supports data?
I find  missing data, for example:

select *
from supports
where  entity_id = '580336659'

returns nothing, but in the site I can see plenty  of supports http://www.obudget.org/#entity/580336659/2017/main

**Comment by akariv** [comment]
Gov supports website has been dows for a few months now... but this is for
another issue.
