### ISSUE TITLE
[Data] [Infra] procurement-tenders-exemptions should update existing items (periodically or by other logic)

### ISSUE THREAD

**Issue by OriHoch** [OpenBudget/budgetkey-data-pipelines#38]
### reproduction
* procurement-tenders-exemptions pipeline runs daily and inserts new exemption (after #13 is merged)
* after a week an exemption's details are updated

#### expected
* the updated exemption's details should be updated

#### actual
* only new exemptions are inserted (based on whether they exist based on ID)

### notes
* should consider some logic for how / when to update
* @akariv suggested a solution based on the exemption status:
  * > This will allow in the future more correct behaviours, such as periodically re-scraping records that are still "in progress" (i.e data might still be changing) and not scraping records that have been concluded.
* a solution which doesn't rely on the underlying data - 
  * have a column of last scrape date in DB
  * on every daily run (or a different, maybe hourly run) - update a limited number of exemptions which were updated the earliest
  * on every updated exemption the last scrape date is updated
  * that wait, it will slowly go over all exemptions and update them

**Comment by OriHoch** [comment]
@akariv was it closed on purpose? if yes, why?

**Comment by OriHoch** [comment]
it's not fixed or done as far as I know

**Comment by akariv** [comment]
You're right, my mistake

**Comment by akariv** [comment]
Suggested algorithm (probably should be made somewhat generic as this need might arise in other places as well):

- Each record will hold a `last_updated_at` field and a `ttl` field
- `last_updated_at` will hold the last time this record was fetched from source
- `ttl` will start with value `1 day`

Algorithm:
- When deciding whether to fetch the record again, we check `last_updated_at + ttl > now?`
   - If yes, then we fetch and update `last_updated_at`
      - If new data equals current data, we set `ttl = 2*ttl`
      - Otherwise, we set `ttl = 1`
   - If not, then we skip fetching and don't change the record

This means that records which ceased to change, will be fetched less and less frequently
