### ISSUE TITLE
[Data] [Scrape] Cooperative Registrar

### ISSUE THREAD

**Issue by akariv** [OpenBudget/budgetkey-data-pipelines#41]
https://apps.moital.gov.il/CooperativeSocieties/

- [x] Create new pipeline under 'entities/cooperatives'
- [x] Scrape the cooperative registrar. Note that they have an API that allows getting all the data as JSON in one request.
- [x] Connect to all entities grand list, with the proper kind ('cooperative')

**Comment by danielbraun** [comment]
I've begun working on it - playing around with their API to see what it's capable of.

**Comment by danielbraun** [comment]
API endpoint:

URL: https://apps.moital.gov.il/CooperativeSocieties/api/Agudot/GetAgudotInfo
Method: GET
The API respects the Accept header, so make sure you request JSON.

Query params:
* N_AGUDA: ""
* C_STATUS_MISHPATI ""
* C_YESHUV: ""
* C_SUG: ""
* SHEM_AGUDA: ""
* FromRowNum: 0 (used for pagination offset)
* quantity: 100 (limit, maximum is 100)

**Comment by OriHoch** [comment]
example api urls - [page 1](https://apps.moital.gov.il/CooperativeSocieties/api/Agudot/GetAgudotInfo?N_AGUDA=&C_STATUS_MISHPATI=&C_YESHUV=&C_SUG=&SHEM_AGUDA=&FromRowNum=0&quantity=15), [page 2](https://apps.moital.gov.il/CooperativeSocieties/api/Agudot/GetAgudotInfo?N_AGUDA=&C_STATUS_MISHPATI=&C_YESHUV=&C_SUG=&SHEM_AGUDA=&FromRowNum=16&quantity=15) .. iterate until no more results ... [example last page](https://apps.moital.gov.il/CooperativeSocieties/api/Agudot/GetAgudotInfo?N_AGUDA=&C_STATUS_MISHPATI=&C_YESHUV=&C_SUG=&SHEM_AGUDA=&FromRowNum=9999&quantity=15)

**Comment by OriHoch** [comment]
@danielbraun 
are you still working on it or is the issue available for working on?

**Comment by danielbraun** [comment]
I am not. You can work on it.

**Comment by OriHoch** [comment]
should work after #61 is merged and deployed

**Comment by OriHoch** [comment]
works, pipeline ran, got data in DB table `cooperatives`
