### ISSUE TITLE
[Data] [Legal] FOI request the list of public good companies

### ISSUE THREAD

**Issue by akariv** [OpenBudget/budgetkey-data-pipelines#42]
@shevyk

Later:
- [ ] Get the list of public good companies from company registrar using the suffix (חל״צ)
- [ ] Make sure that the lists match
- [ ] If so, continue to scrape data on the public good companies from guidestar as well
- [ ] Combine the guidestar details with the company registrar details.

**Comment by shevyk** [comment]
[FOI request](https://drive.google.com/file/d/0B_sHNpzciPA6MnVjNE9GbGpMRWs/view?usp=sharing) submitted.
