### ISSUE TITLE
[Data] [Enrichment] Geocode addresses of entities

### ISSUE THREAD

**Issue by akariv** [OpenBudget/budgetkey-data-pipelines#51]
Add a processor that does some geocoding for addresses of entities.

- [x] Make sure requests are cached locally so that multiple requests for the same address will be resolved without hitting network.
- [ ] Collect statistics on misses
- [ ] Employ heuristics for improving the geolocation success rate without causing false positives

**Comment by OriHoch** [comment]
* do you have a geocoding service or library you prefer or suggest to use?
* do you have suggestion regarding the heuristics logic? or some example

**Comment by akariv** [comment]
I usually use https://geocoder.readthedocs.io/ which is a front to multiple geocoding services.
One of the heuristics would be to use more than one service to improve accuracy (or validate the results).

Other heuristics:
- Make sure the response is indeed of a high accuracy geolocation (i.e. of type 'address' and not 'city' or 'neighborhood').
- Detect common patterns in addresses which might be removed for improved accuracy (e.g. "ת.ד. XXX" or the "אצל משה בחצר" suffix). 

We can start with the addresses of NGOs in our database as a test run.

**Comment by OriHoch** [comment]
:( the pipeline didn't run because it has dependency on entities/all pipeline

I think this dependency can be dropped, we really just need entities sql table, don't care about the other pipelines

**Comment by OriHoch** [comment]
after #63 is merged - the pipeline should run

**Comment by OriHoch** [comment]
looks like pipeline ran, many entities have coordinates, but I guess we encounter rate limit, because also a lot of valid addresses don't have coordinates

**Comment by akariv** [comment]
We should probably retry those - and detect the reason for the error to see
if it should be treated as a permanent problem or as a temporary one.
wdyt?

**Comment by OriHoch** [comment]
Many improvements to the geocode processor in PR #67  - need to merge and also set some provider API keys - to make sure we don't hit limits

google free is limited to 2500 requests per day while we have ~200,000 entities with what seem like valid place names in DB

After the changes in #67 it will be possible to use google free, the processor will only make 2500 requests per day, so it will take a while..

**Comment by OriHoch** [comment]
waiting for DB schema changes from PR #67 to be done, and pipelines to run
