### ISSUE TITLE
investigate error: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk.

### ISSUE THREAD

**Issue by OriHoch** [OpenBudget/budgetkey-data-pipelines#60]
hasn't happened again, it might have been fixed, but worth to investigate and ensure it's indeed fixed

https://gist.github.com/OriHoch/76676e82f4b02053894557843468f2d2

**Comment by akariv** [comment]
I've seen this happen as well. 
Not sure why it happened, but restarting the Docker container (without reusing volumes) fixed the problem - although it's not a good solution, obviously.
