### ISSUE TITLE
requests to docker cloud CI return 404

### ISSUE THREAD

**Issue by OriHoch** [OpenBudget/budgetkey-data-pipelines#70]
there is a failure from docker cloud but I can't debug it because all requests return 404

from PR #69 - https://cloud.docker.com/redirect?resource_uri=/api/audit/v1/action/b267b9a7-e2a8-4e83-81d3-4a2ac4938613/

![image](https://user-images.githubusercontent.com/1198854/29515902-f3e4765c-8676-11e7-9965-249183a8fb1e.png)

**Comment by akariv** [comment]
Because of how docker cloud works, view permission is only granted to specific users.
I can add anyone who is working on the project, but it's on a name-by-name basis.
