### ISSUE TITLE
should refactor the exemption publishers mock processor - find a better solution

### ISSUE THREAD

**Issue by OriHoch** [OpenBudget/budgetkey-data-pipelines#9]
### background
* the `add_publisher_urls_resource` processor is doing some http requests
* when running unit tests we don't want to make remote requests - both to keep them fast and because it's not reliable
* for that reason, I separated the code into a standalone class (`ExemptionsPublisherScraper`) - which handles making of the http requests and returning the data. 
* this class can then be unit tested directly without the pipelines framework

### the problem
* while the unit test for the class tests most scenarios, we still need to test the `add_publisher_urls_resource` processor - in the context of the pipelines framework
* we need to have a way to call a processor with mock=true parameter which will cause it not to make the http requests but instead return some mock data

### expected solution
* should have a solution which separates the mock code from the library / processor code
* the `add_publisher_urls_resource` should not contain any code which is used only for mocks or for testing

### actual solution
* currently the mock code is in the `add_publisher_urls_resource` processor

**Comment by OriHoch** [comment]
@akariv:
> Take a look at the work done here, perhaps it would be useful for mocking:
https://github.com/frictionlessdata/datapackage-pipelines/commit/748c067e87366b21404c39ff319c1240a964393f

**Comment by OriHoch** [comment]
@akariv  - that code is useful for fixture tests but does not solve the problem of mocking a processor

**Comment by OriHoch** [comment]
I have a similar problem in [beit-Hatfutsot/mojp-dbs-pipelines](https://github.com/beit-Hatfutsot/mojp-dbs-pipelines) - currently the best solution I found is to have a class doing all the work of ingest / spew - just in the form of a class. This class can be extended in unit tests to allow for mocking.

Some examples:
* https://github.com/Beit-Hatfutsot/mojp-dbs-pipelines/blob/master/mojp_dbs_pipelines/clearmash/processors/download.py
* https://github.com/Beit-Hatfutsot/mojp-dbs-pipelines/blob/master/mojp_dbs_pipelines/clearmash/processors/convert.py

**Comment by brew** [comment]
@OriHoch 

From your issue description, this looks exactly like the type of problem I was trying to address with the `mock_processor_test` function (https://github.com/frictionlessdata/datapackage-pipelines/pull/46). The idea is to be able to test the processor with predictable inputs (what it ingests) in a way that allows certain parts to be easily mocked.

I have similar requirements to test processors that make calls to external services, so I want to mock the response from those services in my tests, not in my processor code. Here's an example test for a processor that calls to the Github API: https://github.com/okfn/measure/blob/259abf127d1811eb2208665794c8cc5c759d9bb4/tests/test_processors.py#L27

**Comment by OriHoch** [comment]
yes, mock_requests is a good option. 

I personally prefer not to have implementation details (like using the requests library) in the tests which is why I prefer to use mock classes which override specifc functions which contain the implementation details.
