### ISSUE TITLE
Guidestar scarper: Add association (professional) Domains and subdomains 

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-data-pipelines#90]
1. add the subdomain value, as it appears in the association page:

![image](https://user-images.githubusercontent.com/3581741/32696739-d4d76960-c788-11e7-8b72-6e9812f1d00d.png)

2. classify subdomains by main domains categories, as they appear on 
![image](https://user-images.githubusercontent.com/3581741/32696770-8daa3fd0-c789-11e7-99c7-121c1953c53e.png):

**Comment by noamoss** [comment]
@akariv 
1. please add the technical description (i.e. preferred key name, etc.)
2. not sure about the ability to scrape the categories (no.2), please advise.

**Comment by akariv** [comment]
There's a unique mapping between the value that's scrapable (e.g. מוסדות חינוך) to its parent activity group. We can either scrape this page or prepare a manual list.

**Comment by noamoss** [comment]
>We can either scrape this page or prepare a manual list.

If both ways cost them same effort, I believe we better scrape it, just to track and update automatically future changes in categories. Not a must, though.  Please update what method was chosen.

**Comment by akariv** [comment]
http://data.obudget.org/queries/1442/source
