### ISSUE TITLE
Guidestar Scraper: split activity areas values 

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-data-pipelines#91]
Activity areas should be treated as a multi-value field.

See the current problem in the screenshot below:

![image](https://user-images.githubusercontent.com/3581741/33032631-85725e18-ce2a-11e7-8716-0048b07d57b5.png)

**Comment by noamoss** [comment]
@akariv please estimate the time required for the task

**Comment by akariv** [comment]
Done, added a new field (`association_activity_region_list`)
