### ISSUE TITLE
Bank Of Israel scraper

### ISSUE THREAD

**Issue by akariv** [OpenBudget/budgetkey-data-pipelines#92]
There are a lot of data series in the Bank Of Israel website.

Develop a processor that can be configured to a list of such series and creates a dataset with the following columns: `series-name, timestamp, value`

Sample link:
http://www.boi.org.il/he/DataAndStatistics/Pages/SeriesSearchBySubject.aspx?Level=4&sId=16

And the data can be scraped from:
http://www.boi.org.il/he/DataAndStatistics/Pages/SeriesData.aspx?SeriesCode=IRW_@FRN.M&DateStart=01/01/1975&DateEnd=31/08/2017&Level=4&Sid=16

**Comment by asfuna** [comment]
#121
