### ISSUE TITLE
Guidestar scarper: Association_annual_turnover to number

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/budgetkey-data-pipelines#93]
![image](https://user-images.githubusercontent.com/3581741/33058061-60dc842c-ce96-11e7-94cd-06854b59e338.png)

Remove the NIS sign, keep the value, so we can calculate AVG, MEDIAN and MOD

**Comment by akariv** [comment]
Fixed via: https://github.com/OpenBudget/budgetkey-data-pipelines/commit/c40a16b142e781ad88a38f75dfbc99034d171696#diff-1cc5d430254194ef98132d68fd2ace04
